### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by keisuke-kk** [keisuke-kk/chat-space#9]
# IPアドレス
13.230.105.209

**Comment by mo1015** [comment]
神田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバーの「グループ名」、「最新メッセージ」の色が見本と異なる、下線が入っている
○contents上部の「メンバー名」の前の「Member :」が抜けている、その下の線が入っていない**

<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/80267683-49aa1880-86dd-11ea-8e04-681b0b0a00fa.png">

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisuke-kk** [comment]
諸所、修正しました！

**Comment by mo1015** [comment]
再提出ありがとうございます！
確認させて頂きましたが、修正箇所問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
